from enum import Enum


class PlayerActionEnum(Enum):

    HOMERUN = 'HOMERUN'
    SINGLE = 'SINGLE'
    DOUBLE = 'DOUBLE'
    TRIPLE = 'TRIPLE'

    FLYBALL = 'FLYBALL'
    # FLYBALLB = 'FLYBALL'
    # FLYBALLC = 'FLYBALL'
    # FLYBALLX = 'FLYBALL'

    GROUNDBALL = 'GROUNDBALL'
    # GROUNDBALL = 'GROUND-BALL'
    # GROUNDBALLC = 'GROUNDBALL'
    # GROUNDBALLX = 'GROUNDBALL'

    POPOUT = 'POPOUT'

    FOULOUT = 'FOULOUT'

    LINEOUT = 'LINEOUT'
    WALK = 'WALK'
    STRIKEOUT = 'STRIKEOUT'
    CATCHER_CARD = "CATCHER'S CARD"

    NULL = 'NULL'
